### ISSUE TITLE
Broken when viewed inside related entries modal

### ISSUE THREAD

**Issue by petehjfd** [craft-snippets/Craft-quick-filters#5]
Hi

We've added a filter to a particular section, which all works fine.

However, we have an Entries field that allows admins to relate an entry to entries from that same section.  In the Entries modal, the Quick Filters dropdown is very broken (see screenshot).

<img width="1067" alt="Screenshot 2023-01-10 at 12 11 31" src="https://user-images.githubusercontent.com/29060670/211549267-a4848745-ef47-492c-9b1c-9442a789fbc7.png">

Craft 4.3.6
Quick Filters 2.2.0

Thanks

**Comment by petehjfd** [comment]
Hi, any thoughts on this?

Thanks

**Comment by piotrpog** [comment]
@petehjfd 
Hi,
thank you for bringing my attention to this. I will get if fixed son, probably within a week.

**Comment by petehjfd** [comment]
Thanks @piotrpog, appreciate your help!

**Comment by petehjfd** [comment]
Hi @piotrpog - just wondering if you've had any luck with this?

Thanks

**Comment by piotrpog** [comment]
@petehjfd 
Hi. Sorry for the delay - i was waiting for response from Craft support (some of the things this plugin uses internally are not documented). Today i sent another email - hope i will get response soon and will be able to implement the fix.

**Comment by piotrpog** [comment]
@petehjfd 
This was fixed in recent release.
Sorry for long wait time!
Small comment - due to some intricacies of how Craft modal works, when opening dropdown in modal, you can only close it by clicking on dropdown label again, while in regular element index you can also close it by clicking outside.
Im not really sure how to tackle it without rewriting dropdown library. But i think it is only mild inconvinience.

**Comment by petehjfd** [comment]
@piotrpog Thank you so much for getting this resolved.  Our client will be very happy! 😀

**Comment by piotrpog** [comment]
@petehjfd 
Glad to hear that.
